baseurl = "https://www.crmtdigital.com/"
description = "The marketing operations experts."
disableKinds = "taxonomyTerm"
languageCode = "en-gb"
preserveTaxonomyNames = true
title = "CRMT Digital"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Insights"
url = "/insights"
weight = 5
[[menu.main]]
name = "Excellence Hub"
url = "/excellence-hub"
weight = 4
[params]
mainSections = ["marketing", "technology", "martech", "opinion"]
[permalinks]
post = "/:title/"
who-we-work-with = "/customers/:slug"
[taxonomies]
tag = "tags"
