baseurl = "https://www.crmtdigital.com/"
languageCode = "en-gb"
title = "CRMT Digital"
description = "The marketing operations experts."
preserveTaxonomyNames = true
disableKinds = "taxonomyTerm"
[permalinks]
  post = "/:title/"
  who-we-work-with = "/customers/:slug"
 [taxonomies]
  tag = "tags"
[params]
  mainSections = ["marketing", "technology","martech","opinion"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
