baseurl = "https://www.crmtdigital.com/"
languageCode = "en-gb"
title = "CRM Technologies"
preserveTaxonomyNames = true
disableKinds = ["taxonomyTerm"]
[permalinks]
  post = "/:title/"
[params]
  mainSections = ["marketing", "technology","martech","opinion"]
