baseurl = "https://www.crmtdigital.com/"
description = "The marketing operations experts."
disableKinds = "taxonomyTerm"
languageCode = "en-gb"
preserveTaxonomyNames = true
title = "CRMT Digital"
[markup.goldmark.renderer]
unsafe = true
[params]
mainSections = ["marketing", "technology", "martech", "opinion"]
[permalinks]
post = "/:title/"
who-we-work-with = "/customers/:slug"
[taxonomies]
tag = "tags"
