baseurl = "https://www.crmtdigital.com/"
languageCode = "en-gb"
title = "CRM Technologies"
preserveTaxonomyNames = true
disableKinds = ["taxonomyTerm"]
[permalinks]
  post = "/:title/"
  who-we-work-with = "/customers/:slug"
 [taxonomies]
  category = "categories"
  tag = "tags"
[params]
  mainSections = ["marketing", "technology","martech","opinion"]
