baseurl = "https://zealous-liskov-3ee2f4.netlify.com/"
languageCode = "en-gb"
title = "CRM Technologies"
description = "The marketing operations experts."
preserveTaxonomyNames = true
[permalinks]
  post = "/:title/"
  who-we-work-with = "/customers/:slug"
 [taxonomies]
  category = "categories"
  tag = "tags"
[params]
  mainSections = ["marketing", "technology","martech","opinion"]
