---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/_index.html
  label: Home Page
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  exclude: _index.html
  new_doc_ext: html
  templates:
  - page
- type: directory
  path: content/insights
  label: Blog Post
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - blog-post
  - infographic
  - resource
  - slideshare
  - video
- type: directory
  path: content/who-we-work-with
  label: Case Studies
  create: documents
  match: "**/*"
  exclude: _index.html
  new_doc_ext: html
  templates:
  - case-study
- type: document
  path: data/logos.json
  label: Customer Logos
- type: document
  path: data/team.json
  label: Executive Biographies
- type: document
  path: data/banners.json
  label: Home Page Banners
- type: document
  path: data/careers.json
  label: Job Postings
- type: directory
  path: content/excellence-hub
  label: Resources
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - resource
  - infographic
  - slideshare
  - video
- type: directory
  path: content/ty
  label: Thank You Pages
  create: all
  match: "**/*"
  exclude: _index.html
upload_dir: sites/default/files
public_path: sites/default/files
front_matter_path: https://static.crmtechnologies.com/sites/default/files
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=development
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
